# Generated by Django 5.2.4 on 2025-07-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_purchase_amount_paid_purchase_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="event_name",
            field=models.CharField(default="empty", max_length=200),
            preserve_default=False,
        ),
    ]
